# Generated by Django 5.2.4 on 2025-07-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='matched_lost_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'Lost'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_matches', to='portal.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Recovered', 'Recovered')], default='Open', max_length=10),
        ),
    ]
