services:
  - type: web
    name: lostfound-portal
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd lostfound_project && gunicorn lostfound_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: lostfound_project.settings_production
      - key: ADMIN_USERNAME
        value: iamprabesh
      - key: ADMIN_PASSWORD
        value: iamprabesh@123
      - key: ADMIN_EMAIL
        value: iamprabesh2003@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: lostfound-db
          property: connectionString

databases:
  - name: lostfound-db
    databaseName: lostfound_db
    user: lostfound_user
    plan: free
